### ISSUE TITLE
Add trophic incoherence?

### ISSUE THREAD

**Issue by BazilSansom** [WouterSpekkink/gephi-plugins#6]
Trophic levels implemented.  Let's use these to also calculate and return trophic incoherence?

Return under "Network overview" as "Trophic incoherence"

Plug levels into equation 2.7 from MacKay et al. (2020)
https://doi.org/10.1098/rsos.201138

Example (pseudo)code:
  `h=trophic_levels`
  `H=meshgrid(h)-meshgrid(h)'-1`
  `H=H.^2`
  `F_0=sum(sum(W))^-1*sum(sum((W.*H)))`

**Comment by WouterSpekkink** [comment]
Good idea to include this. I think it will actually be easier to just translate equation 2.7 in the paper directly to Java, because the pseudocode uses functions (in particular meshgrid) for which I cannot quickly find a java equivalent. However, the equation itself looks easy enough to implement. I'll have a stab at this soon.

**Comment by WouterSpekkink** [comment]
Could you have a look at the below, whether you think I translated the equation correctly to Java code?

``` java
             // An attempt to also calculate the trophic incoherence
                
                // First initialize the numinator and denominator
                double numerator = 0.0;
                double denominator = 0.0;
                for (int i = 0; i < component.size(); i++) {
                    for (int j = 0; j < component.size(); j++) {
                        // It only makes sense to do this if there is an edge 
                        if (hgraph.getEdge(nodes[i], nodes[j]) != null) {
                            // Get the weight of the edge between the two nodes
                            double weight = hgraph.getEdge(nodes[i], nodes[j]).getWeight();                
                            // Let's immediately add this to the sum of weights (denominator)
                            denominator += weight;
                            // Get the trophic level of the nodes
                            double hi = results[i];
                            double hj = results[j];
                            // Then we can add to the numerator
                            numerator += weight * ((hi - hj - 1) * (hi -hj - 1));
                        }
                    }
                }
                double F_0 = numerator / denominator;
```

**Comment by WouterSpekkink** [comment]
One thing I just realized is that this calculates the F_0 for each component separately, of which I am not sure if we want that? Could you clarify that?

**Comment by WouterSpekkink** [comment]
I went along and finished adding this part. Currently, the plugin calculates trophic incoherence for each detected component separately, and the statistic is shown in the report (for each component) after the plugin finishes.

If more than 1 component is detected, a column to report the component that eah node is in is also included in the data laboratory. This is for user reference, so that they can identify which nodes belong in which component and then check what the trophic incoherence of that component was.

I think it would be good if you test the latest build (see releases) a bit more, and if it works, I suggest we can close this issue for now.
